//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Product Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Product Category is required")]
        public string Category { get; set; }
        [Required(ErrorMessage = "Product Price is required")]
        public int Price { get; set; }
        [Required(ErrorMessage = "Product Quantity is required")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "Product Short Description is required")]
        [DisplayName("Short Description")]
        public string Short_desc { get; set; }
        [DisplayName("Long Description")]
        public string Long_desc { get; set; }
        [DisplayName("Small Image")]
        public string Small_img { get; set; }
        [DisplayName("Large Image")]
        public string Large_img { get; set; }
    }
}
